### ISSUE TITLE
Document mia's chat flow

### ISSUE THREAD

**Issue by longhpzigvy** [miaconsults/mia#86]
- [x] Create a state machine diagram for ticket's status
- [ ] Create data flow diagrams for mia's data flow
  - [x] Context diagram (Level 0 DFD)
  - [ ] Level 1 DFD
  - [ ] Level 2 DFD
- [ ] Create activity diagrams for message processing
- [ ] Use case would be nice too
